---
name: Make

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make:
    runs-on: windows-latest
    timeout-minutes: 120
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: base-devel autoconf automake libtool tar git wget python perl flex bison gettext-devel pkgconf make mingw-w64-x86_64-gettext-tools mingw-w64-x86_64-gperf mingw-w64-x86_64-nasm mingw-w64-x86_64-yasm mingw-w64-x86_64-cmake mingw-w64-x86_64-toolchain mingw-w64-x86_64-ninja mingw-w64-x86_64-meson mingw-w64-x86_64-nsis mingw-w64-x86_64-itstool mingw-w64-x86_64-gettext-tools
      - name: Build on Windows
        run: |
          gcc -O2 -std=c99 -o ewpi ewpi*.c
          ./ewpi --verbose
